### ISSUE TITLE
Cannot upload file using send_keys_ok

### ISSUE THREAD

**Issue by preaction** [jhthorsen/test-mojo-role-selenium#6]
Selenium allows uploading files into `<input type="file">` fields using `send_keys( $absolute_path_to_file )`. If I try to do it using `send_keys_ok( '[type=file]', $absolute_path_to_file )`, I get an error message about "file not found: U" (because my path starts with `/Users`). This appears to be because the `send_keys_ok( $element, $string )` method always splits up the keys to send them individually. If I use `send_keys_ok( '[type=file]', [ $absolute_path_to_file ] )`, the path string is not split up and the upload works.

Full reproduction case:

```perl

use Mojolicious::Lite;
get '/' => 'index';
post '/' => sub {
    my ( $c ) = @_;
    if ( my $upload = $c->param( 'upload' ) ) {
        $c->render( text => 'SUCCESS: ' . $upload->slurp );
    }
};

use Test::Mojo;
use Test::More;
use Cwd qw( abs_path );
$ENV{TEST_SELENIUM}          //= 1;
$ENV{MOJO_SELENIUM_DRIVER}   ||= 'Selenium::Chrome';
# Does not work, I think problem is in driver
#$ENV{MOJO_SELENIUM_DRIVER}   ||= 'Selenium::Firefox';

my $t = Test::Mojo->with_roles( '+Selenium' )->new->setup_or_skip_all;

$t->navigate_ok( '/' )->status_is( 200 )->wait_for( 'form' );

# DOES NOT WORK, get error about file not found
$t->send_keys_ok( '[type=file]', abs_path( $0 ) );
# WORKS
# $t->send_keys_ok( '[type=file]', [ abs_path( $0 ) ] );

$t->click_ok( '[type=submit]' )->live_text_like( 'body', qr{^SUCCESS:} );

done_testing;

__DATA__
@@ index.html.ep
<form method="POST" enctype="multipart/form-data">
<input name="upload" type="file">
<input type="submit">
</form>
```

I think the best solution would be to not split up keys for the single string version of `send_keys_ok()`, allowing users to split up keystrokes themselves with the arrayref version if they so choose.

EDIT: Further, if the `ref` check in `send_keys_ok` was specifically for `ref $_ eq 'SCALAR'`, I could pass Mojo::File objects directly to `send_keys_ok` and have it just work.

**Comment by jhthorsen** [comment]
Two things about send_keys_ok():

1. The behaviour is not documented.
2. e5afce2a26bdbaca4a133a978764967ca147b119 has no description of why I started doing split, but from my recollection it was because I wanted it to simulate normal keyboard press in the most common case.

I don't understand your last suggestion. Why not just check `$keys->isa('Mojo::File')` or just stringify anything thas `can('to_string')`  instead of checking `ref SCALAR`?

I also wonder if the automatic split should be disabled and just pass the string along. I could enable the splitting with a hash-ref instead: `send_keys_ok(..., {split =>  ....})`. Maybe that would be less confusing?

One last thing: I don't think "Cannot upload file using send_keys_ok" is accurate. Can you change the title of the issue?

**Comment by jhthorsen** [comment]
Going to close this, since no feedback has been provided.
